### PR TITLE
Fix securecomm address & refactor arming & API calls

### PR DESCRIPTION
**Pull request by jouwdan**
Changes made:

- Replace secureCommAddress with api request to get one
- Current app version (on iOS at least?) is 1.0.2, so dropped that down
- Refactored API calls to private function
- Refactored arming & disarming to 1 private function

### CODE REVIEW

**Comment by jouwdan** [comment]
looks like the secureCommAddress actually comes as a response on the getSystemStatus in the API, so i've updated the initialization to get the system status and set the self.secureCommAddress that way.

image

**Comment by jouwdan** [comment]
OK i've manually imported this code into home assistant - works a treat. :)

image

**Comment by jouwdan** [comment]
Tested current push in Home Assistant along with manually testing. Works OK for me.

image

**Comment by jasonmadigan** [comment]
thanks @jouwdan - these changes look good. Good to know that there are several API endpoints depending on alarm version as well.

**Comment by jasonmadigan** [comment]
I'll be working on a ha-hkc release in the next day or two.

**Pull request merged**
